import json
import os
import chromadb
from chromadb.utils import embedding_functions
from tqdm import tqdm
from pathlib import Path

# --- CONFIGURATION ---
CHUNKS_FILE = "data/chunks.jsonl"
DB_PATH = "./chroma_db"
COLLECTION_NAME = "small_business_kb"
EMBEDDING_MODEL_NAME = "all-MiniLM-L6-v2"

class EmbedderSaver:
    def __init__(self, db_path: str = DB_PATH, collection_name: str = COLLECTION_NAME):
        # 1. Initialize Chroma Client (Persistent storage)
        self.client = chromadb.PersistentClient(path=db_path)
        
        # 2. Set up the embedding function
        self.embedding_fn = embedding_functions.SentenceTransformerEmbeddingFunction(
            model_name=EMBEDDING_MODEL_NAME
        )
        
        # 3. Create or Get the collection
        self.collection = self.client.get_or_create_collection(
            name=collection_name,
            embedding_function=self.embedding_fn
        )

    def load_jsonl(self, file_path: str):
        """Loads the chunks generated by the previous script."""
        chunks = []
        if not os.path.exists(file_path):
            print(f"Error: {file_path} not found.")
            return []
        
        with open(file_path, "r", encoding="utf-8") as f:
            for line in f:
                chunks.append(json.loads(line))
        return chunks

    def save_chunks_to_db(self, chunks):
        """Processes chunks and upserts them into ChromaDB."""
        if not chunks:
            print("No chunks to save.")
            return

        print(f"Embedding and saving {len(chunks)} chunks to ChromaDB...")

        ids = []
        documents = []
        metadatas = []

        for chunk in tqdm(chunks):
            # Helper to get data whether 'chunk' is a dict or a dataclass object
            def get_val(obj, key):
                if isinstance(obj, dict):
                    return obj.get(key)
                return getattr(obj, key, None)

            # Extract IDs and Text
            c_id = get_val(chunk, "chunk_id")
            c_text = get_val(chunk, "embedding_text")
            
            if not c_id or not c_text:
                continue

            ids.append(str(c_id))
            documents.append(c_text)
            
            # Metadata processing
            tags = get_val(chunk, "tags")
            tags_str = ",".join(tags) if isinstance(tags, (list, tuple)) else str(tags or "")

            metadata = {
                "document_title": str(get_val(chunk, "document_title") or "Unknown"),
                "authority": str(get_val(chunk, "authority") or "Unknown"),
                "section_title": str(get_val(chunk, "section_title") or ""),
                "breadcrumb": str(get_val(chunk, "breadcrumb") or ""),
                "page_start": int(get_val(chunk, "page_start") or 0),
                "source_file": str(get_val(chunk, "source_file") or ""),
                "topic_id": str(get_val(chunk, "topic_id") or ""),
                "version": str(get_val(chunk, "version") or ""),
                "tags": tags_str
            }
            metadatas.append(metadata)

        # Batch upsert
        self.collection.upsert(
            ids=ids,
            documents=documents,
            metadatas=metadatas
        )
        print(f"Successfully saved to collection: {self.collection.name}")

    def query(self, user_message: str, n_results: int = 5):
        """Retrieves the most relevant chunks."""
        results = self.collection.query(
            query_texts=[user_message],
            n_results=n_results
        )
        return results

if __name__ == "__main__":
    # Standalone execution logic
    engine = EmbedderSaver()
    if os.path.exists(CHUNKS_FILE):
        data = engine.load_jsonl(CHUNKS_FILE)
        engine.save_chunks_to_db(data)
    else:
        print(f"File {CHUNKS_FILE} not found. Run the chunker first or use pipeline.py")